name = "rfaker"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = "A relational test dataset generator"
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "DavidJS01", repo = "gleam_rfaker" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.31"
simplifile = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.10"
